apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: monitoring
data:
  # Usamos la clave config.yaml para que coincida con el Deployment
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
    exporters:
      # CORRECCIÓN: 'debug' en lugar de 'logging'
      debug:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, prometheus]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.88.0
        args: ["--config=/etc/otelcol/config.yaml"]
        volumeMounts:
        - name: config-vol
          mountPath: /etc/otelcol/config.yaml
          subPath: config.yaml
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 8889
      volumes:
      - name: config-vol
        configMap:
          name: otel-collector-conf
          items:
            - key: "config.yaml" # ESTA CLAVE DEBE EXISTIR EN EL CONFIGMAP
              path: "config.yaml"