apiVersion: v1
kind: Service
metadata:
  name: techwave-service
spec:
  type: LoadBalancer
  selector:
    app: techwave
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80