apiVersion: apps/v1
kind: Deployment
metadata:
  name: techwave-deployment-green
  labels:
    app: techwave
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techwave
      version: v2
  template:
    metadata:
      labels:
        app: techwave
        version: v2
    spec:
      containers:
      - name: techwave-app
        # Cambia esta línea:
        image: yassinelberrak/techwave-app:latest
        ports:
        - containerPort: 3000