apiVersion: apps/v1
kind: Deployment
metadata:
  name: techwave-deployment-blue
  labels:
    app: techwave
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techwave
      version: v1
  template:
    metadata:
      labels:
        app: techwave
        version: v1
    spec:
      containers:
      - name: techwave-app
        image: nginx:alpine 
        ports:
        - containerPort: 80