name: CI/CD TechWave Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yassinelberrak/techwave-app:latest

      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configurar contexto de AKS
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'rg-techwave-devops'
          cluster-name: 'aks-techwave'

      - name: Desplegar en Kubernetes
        run: |
          # 1. Aplicamos ConfigMaps y Secrets (Asegúrate de crearlos o comentar estas líneas si no existen)
          # kubectl apply -f k8s/configmap.yaml
          # kubectl apply -f k8s/secrets.yaml
          
          # 2. Aplicamos los dos despliegues (Blue y Green) para que estén sincronizados
          kubectl apply -f k8s/techwave-blue.yaml
          kubectl apply -f k8s/techwave-green.yaml
          
          # 3. Forzamos el reinicio para que descarguen la imagen 'latest' recién subida
          kubectl rollout restart deployment techwave-deployment-blue
          kubectl rollout restart deployment techwave-deployment-green
          
          # 4. Aplicamos el Service (que es el que decide quién recibe el tráfico)
          kubectl apply -f k8s/service.yaml